language: android
jdk: oraclejdk8
os: linux

notifications:
  email:
    recipients:
        - atmosphere@musala.com

android:
    components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-19
    - extr

cache:
    directories:
        - $HOME/.gradle

install:
    - chmod +x gradlew
    - git clone https://github.com/MusalaSoft/atmosphere-commons.git
    - git clone https://github.com/MusalaSoft/atmosphere-agent-device-lib.git
    - chmod +x travis-scripts/branch-checkout.sh
    - cd atmosphere-commons && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..
    - cd atmosphere-agent-device-lib && ../travis-scripts/branch-checkout.sh
    - ./gradlew build publishToMavenLocal && cd ..

script:
    - ./gradlew build
